### ISSUE TITLE
missing dependencies

### ISSUE THREAD

**Issue by atesin** [TheMulhima/Button-Prompt-Switcher#1]
hi....   thank you so much fir bringing this fantastic tool to HKmodding api !!! ...  i could'n play the game+mods because of the broken HK controller!

however when i started the first time it reported me errors....  so digging a little and after some more restarts i found the problem was due missing and uninformed dependencies....

- HKMirror
- Satchel

please include these dependencies in configuration file, so it installs automatically when install BPS through scarab mod manager or other equivalent mean

thank you

**Comment by TheMulhima** [comment]
I have added them to modlinks thanks
